[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "visutask-backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic~=1.17.1",
    "argon2-cffi~=25.1.0",
    "cachetools~=7.1.8",
    "fastapi[standard]~=0.121.1",
    "httpx~=0.28.1",
    "passlib~=1.7.4",
    "psycopg2-binary~=2.9.11",
    "pydantic-settings~=2.12.0",
    "pydantic~=2.12.4",
    "python-jose[cryptography]~=3.5.0",
    "SQLAlchemy~=2.0.44",
]

[dependency-groups]
dev = [
    "freezegun~=1.5.5",
    "mypy~=2.4.0",
    "pytest-asyncio~=1.4.0",
    "pytest~=9.0.1",
    "respx~=0.23.1",
    "ruff~=0.16.10",
]

[tool.setuptools.packages.find]
where = ["src"]

# Mypy
[tool.mypy]
plugins = ["pydantic.mypy"]

# Ruff
[tool.ruff]
src = ["src"]
line-length = 88 # Explicit default value
indent-width = 4 # Explicit default value

[tool.ruff.lint]
select = [
    "E", # pycode style
    "F", # Pyflakes
    "I", # Isort
]
