/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Create a new user in the database.
         *     - Validates that the email does not exist.
         *     - Validates that the username does not exist.
         *     - Hash the password.
         *     - Return the new created user after filter it.
         */
        post: operations["register_user_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticates the user and returns a JWT.
         *     - Accepts login with 'username' OR 'email'.
         *     - Verifies the password.
         *     - Creates and returns an access token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Board
         * @description Get a board from a given id.
         */
        get: operations["get_board_boards__board_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Board
         * @description Deletes an existing board.
         *     Only the owner of the board can delete it.
         */
        delete: operations["delete_board_boards__board_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Board
         * @description Update an existing board with the send fields.
         *     Only the owner of the board can update it.
         */
        patch: operations["update_board_boards__board_id__patch"];
        trace?: never;
    };
    "/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Boards
         * @description Get all the boards of the authenticated user.
         */
        get: operations["get_user_boards_boards_get"];
        put?: never;
        /**
         * Create Board
         * @description Create a new board.
         *     The new board will be automatically assigned to the authenticated user.
         */
        post: operations["create_board_boards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_id}/lists/{list_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get List
         * @description Get a list from a given id.
         *     Only the owner of the board with the given `board_id` can get it.
         */
        get: operations["get_list_boards__board_id__lists__list_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete List
         * @description Deletes an existing list.
         *     Only the owner of the board with the given `board_id` can delete it.
         */
        delete: operations["delete_list_boards__board_id__lists__list_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update List
         * @description Update an existing list with the send fields.
         *     Only the owner of the board with the given `board_id` can update it.
         */
        patch: operations["update_list_boards__board_id__lists__list_id__patch"];
        trace?: never;
    };
    "/boards/{board_id}/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Board Lists
         * @description Get all the lists of the board.
         *     Only the owner of the board with the given `board_id` can get it
         */
        get: operations["get_board_lists_boards__board_id__lists_get"];
        put?: never;
        /**
         * Create List
         * @description Create a new list.
         *     The new list will be automatically assigned to the board with the given `board_id`.
         *     Only the owner of the board with the given `board_id` can add the new list.
         */
        post: operations["create_list_boards__board_id__lists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_id}/lists/{list_id}/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Card
         * @description Get a card from a given id.
         *     Only the owner of the board with the given `board_id` can get it.
         */
        get: operations["get_card_boards__board_id__lists__list_id__cards__card_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Card
         * @description Deletes an existing card.
         *     Only the owner of the board with the given `board_id` can delete it.
         */
        delete: operations["delete_card_boards__board_id__lists__list_id__cards__card_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Card
         * @description Update an existing card with the send fields.
         *     Only the owner of the board with the given `board_id` can update it.
         */
        patch: operations["update_card_boards__board_id__lists__list_id__cards__card_id__patch"];
        trace?: never;
    };
    "/boards/{board_id}/lists/{list_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get List Cards
         * @description Get all the cards of the list.
         *     Only the owner of the board with the given `board_id` can get it
         */
        get: operations["get_list_cards_boards__board_id__lists__list_id__cards_get"];
        put?: never;
        /**
         * Create Card
         * @description Create a new card.
         *     The new card will be automatically assigned to the list with the given `list_id`.
         *     Only the owner of the board with the given `board_id` can add a new card.
         */
        post: operations["create_card_boards__board_id__lists__list_id__cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tag
         * @description Get a tag from a given id.
         *     Only the owner of the board with the given `board_id` can get it.
         */
        get: operations["get_tag_boards__board_id__tags__tag_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Tag
         * @description Deletes an existing tag.
         *     Only the owner of the board with the given `board_id` can delete it.
         */
        delete: operations["delete_tag_boards__board_id__tags__tag_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Tag
         * @description Update an existing tag with the send fields.
         *     Only the owner of the board with the given `board_id` can update it.
         */
        patch: operations["update_tag_boards__board_id__tags__tag_id__patch"];
        trace?: never;
    };
    "/boards/{board_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Board Tags
         * @description Get all the tags of the board.
         *     Only the owner of the board with the given `board_id` can get it
         */
        get: operations["get_board_tags_boards__board_id__tags_get"];
        put?: never;
        /**
         * Create Tag
         * @description Create a new tag.
         *     The new tag will be automatically assigned to the board with the given `board_id`.
         *     Only the owner of the board with the given `board_id` can add the new tag.
         */
        post: operations["create_tag_boards__board_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inbox */
        get: operations["get_inbox_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Card
         * @description Move a card between lists (or the same list, within the same board or to another).
         *     Also change the position of the card with (place the card at the bottom of the list if not specified).
         *     Verify that the current user owns both the source and destination lists.
         */
        post: operations["move_card_cards__card_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach Tag
         * @description Associate an existing tag with a card.
         */
        post: operations["attach_tag_cards__card_id__tags__tag_id__post"];
        /**
         * Detach Tag
         * @description Removes an existing tag from a card.
         */
        delete: operations["detach_tag_cards__card_id__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Board */
        Board: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            user: components["schemas"]["UserSubschema"];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagSubschema"][];
            /**
             * Lists
             * @default []
             */
            lists: components["schemas"]["ListSubschema"][];
        };
        /** BoardCreate */
        BoardCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            /**
             * Default Tag Colors
             * @default []
             */
            default_tag_colors: string[];
        };
        /** BoardSubschema */
        BoardSubschema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Image Url */
            image_url: string | null;
        };
        /** BoardUpdate */
        BoardUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Card */
        Card: {
            /** Name */
            name: string;
            /** Text */
            text?: string | null;
            /** Is Done */
            is_done: boolean;
            /** Position */
            position: number;
            /** Due Date */
            due_date?: string | null;
            /** Id */
            id: number;
            /** List Id */
            list_id: number;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagSubschema"][];
            list: components["schemas"]["ListSubschema"];
        };
        /** CardCreate */
        CardCreate: {
            /** Name */
            name: string;
            /** Text */
            text?: string | null;
        };
        /** CardMove */
        CardMove: {
            /**
             * Destination List Id
             * @description The ID of the list to which you want to move the card.
             */
            destination_list_id: number;
            /**
             * Destination List Position
             * @description The new position of the list (gather or equal than 1)
             */
            destination_list_position?: number | null;
        };
        /** CardSubschema */
        CardSubschema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Text */
            text: string | null;
            /** Is Done */
            is_done: boolean;
            /** Position */
            position: number;
            /** Due Date */
            due_date: string | null;
            /** Tags */
            tags: components["schemas"]["TagSubschema"][];
        };
        /** CardUpdate */
        CardUpdate: {
            /** Name */
            name?: string | null;
            /** Text */
            text?: string | null;
            /** Is Done */
            is_done?: boolean | null;
            /** Due Date */
            due_date?: string | null;
        };
        /** HTTPError */
        HTTPError: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Inbox */
        Inbox: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            user: components["schemas"]["UserSubschema"];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagSubschema"][];
            /**
             * Lists
             * @default []
             */
            lists: components["schemas"]["InboxList"][];
        };
        /** InboxList */
        InboxList: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Cards
             * @default []
             */
            cards: components["schemas"]["CardSubschema"][];
        };
        /** List */
        List: {
            /** Name */
            name: string;
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Board Id */
            board_id: number;
            board: components["schemas"]["BoardSubschema"];
            /**
             * Cards
             * @default []
             */
            cards: components["schemas"]["CardSubschema"][];
        };
        /** ListCreate */
        ListCreate: {
            /** Name */
            name: string;
        };
        /** ListSubschema */
        ListSubschema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Board Id */
            board_id: number;
        };
        /** ListUpdate */
        ListUpdate: {
            /** Name */
            name?: string | null;
        };
        /** Tag */
        Tag: {
            /** Name */
            name?: string | null;
            /**
             * Color
             * @description Hex color code (e.g. #FF0000)
             */
            color: string;
            /** Id */
            id: number;
            /** Board Id */
            board_id: number;
            board: components["schemas"]["BoardSubschema"];
            /**
             * Cards
             * @default []
             */
            cards: components["schemas"]["CardSubschema"][];
        };
        /** TagCreate */
        TagCreate: {
            /** Name */
            name?: string | null;
            /**
             * Color
             * @description Hex color code (e.g. #FF0000)
             */
            color: string;
        };
        /** TagSubschema */
        TagSubschema: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Color */
            color: string;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Name */
            name?: string | null;
            /** Color */
            color?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** User */
        User: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Boards
             * @default []
             */
            boards: components["schemas"]["BoardSubschema"][];
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserSubschema */
        UserSubschema: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_user_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Username or email are already registered */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Unauthorized: Incorrect username or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_boards__board_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_board_boards__board_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tryed to delete the inbox */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_board_boards__board_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tryed to modify the inbox */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_boards_boards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSubschema"][];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    create_board_boards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_list_boards__board_id__lists__list_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_list_boards__board_id__lists__list_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tryed to delete inbox list */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_list_boards__board_id__lists__list_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tryed to modify inbox list */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_lists_boards__board_id__lists_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"][];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_list_boards__board_id__lists_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tryed to create list in the Inbox */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_boards__board_id__lists__list_id__cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_boards__board_id__lists__list_id__cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_boards__board_id__lists__list_id__cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_list_cards_boards__board_id__lists__list_id__cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"][];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_card_boards__board_id__lists__list_id__cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                list_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tag_boards__board_id__tags__tag_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_boards__board_id__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_boards__board_id__tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_tags_boards__board_id__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_boards__board_id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Tryed to create tag in Inbox */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Board not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inbox_inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inbox"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
    move_card_cards__card_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Position out of the range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Trying to move a card without owning the card or list */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Card or List not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_tag_cards__card_id__tags__tag_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Card or Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_tag_cards__card_id__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Card or Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
        };
    };
}
