"""create Board model and User <-> Board relationship

Revision ID: 4a1cc77b4a4b
Revises: 803d2925ce45
Create Date: 2025-11-13 18:05:56.440584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1cc77b4a4b'
down_revision: Union[str, Sequence[str], None] = '803d2925ce45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
