"""List position

Revision ID: 86ec981024eb
Revises: adc3c63bb6f3
Create Date: 2026-01-23 12:06:12.186678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ec981024eb'
down_revision: Union[str, Sequence[str], None] = 'adc3c63bb6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('lists', sa.Column('position', sa.Integer(), nullable=True))
    op.execute("UPDATE lists SET position = 1 WHERE position IS NULL")
    with op.batch_alter_table('cards') as batch_op:
        batch_op.alter_column('position', nullable=False)
    op.create_index(op.f('ix_lists_position'), 'lists',
                    ['position'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lists_position'), table_name='lists')
    op.drop_column('lists', 'position')
    # ### end Alembic commands ###
