"""Board image_url field

Revision ID: adc3c63bb6f3
Revises: 02c92e25e679
Create Date: 2025-12-17 18:04:20.351234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc3c63bb6f3'
down_revision: Union[str, Sequence[str], None] = '02c92e25e679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'image_url')
    # ### end Alembic commands ###
