"""fix - make list position not null

Revision ID: b14d8e759ed7
Revises: 86ec981024eb
Create Date: 2026-08-17 11:17:15.382191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14d8e759ed7'
down_revision: Union[str, Sequence[str], None] = '86ec981024eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
