"""Add is_inbox column in Board

Revision ID: ba07aa64fbde
Revises: 1fe1d14b7ba9
Create Date: 2025-11-18 11:57:35.133273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba07aa64fbde'
down_revision: Union[str, Sequence[str], None] = '1fe1d14b7ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add a temporal default value 'false'.
    op.add_column('boards', sa.Column('is_inbox', sa.Boolean(),
                  nullable=False, server_default=sa.text('false')))
    # Delete the default value after applying the changes
    op.alter_column('boards', 'is_inbox', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'is_inbox')
    # ### end Alembic commands ###
