"""background image discriminated object

Revision ID: ba407c336784
Revises: b14d8e759ed7
Create Date: 2026-08-17 12:17:20.300169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba407c336784'
down_revision: Union[str, Sequence[str], None] = 'b14d8e759ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('background_type', sa.Enum('image', 'gradient', 'solid', native_enum=False), nullable=True))
    op.add_column('boards', sa.Column('background_value', sa.String(length=511), nullable=True))
    op.add_column('boards', sa.Column('background_blur_hash', sa.String(length=511), nullable=True))
    # ### end Alembic commands ###
    op.execute( # Migrates image_url -> background_type & background_value
        """
        UPDATE boards
        SET background_type = 'image',
            background_value = image_url
        WHERE image_url IS NOT NULL AND image_url != ''
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'background_blur_hash')
    op.drop_column('boards', 'background_value')
    op.drop_column('boards', 'background_type')
    # ### end Alembic commands ###
