"""Card position

Revision ID: cb1a4b0cfd38
Revises: ba07aa64fbde
Create Date: 2025-11-20 12:05:03.787090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1a4b0cfd38'
down_revision: Union[str, Sequence[str], None] = 'ba07aa64fbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('cards', sa.Column('position', sa.Integer(), nullable=True))
    op.execute("UPDATE cards SET position = 1 WHERE position IS NULL")
    with op.batch_alter_table('cards') as batch_op:
        batch_op.alter_column('position', nullable=False)

    op.create_index(op.f('ix_cards_position'), 'cards',
                    ['position'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_position'), table_name='cards')
    op.drop_column('cards', 'position')
    # ### end Alembic commands ###
